name: almuchtariyah_app
description: "Ashidqi (Sahabat Ibadah Harian) - Islamic Daily Worship App"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_animate: ^4.5.0
  google_fonts: ^6.2.1
  provider: ^6.1.2
  intl: ^0.19.0
  shared_preferences: ^2.2.2
  http: ^1.2.0
  adhan: ^2.0.0+1
  geolocator: ^14.0.2
  audioplayers: ^6.5.1
  scrollable_positioned_list: ^0.3.8
  hijri: ^3.0.0
  geocoding: ^4.0.0
  flutter_local_notifications: ^17.0.0
  timezone: ^0.9.0
  sqflite: ^2.4.2
  path: ^1.9.1
  flutter_compass: ^0.8.1
  permission_handler: ^12.0.1
  sensors_plus: ^7.0.0
  flutter_map: ^8.2.2
  latlong2: ^0.9.1
  home_widget: ^0.9.0
  url_launcher: ^6.3.2
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/audio/
    - assets/icon/
